# Generated by Django 3.0.6 on 2020-06-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=6)),
                ('existencia', models.IntegerField(default=0)),
                ('fecha_publicacion', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Producto')),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Categoria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Vendedor'),
        ),
        migrations.CreateModel(
            name='Perfil_Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('direccion', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado', models.BooleanField(default=True)),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now=True)),
                ('fecha_envio', models.DateField()),
                ('usuario_comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Comprador')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(blank=True, upload_to='')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('descuento', models.CharField(max_length=6)),
                ('total', models.CharField(max_length=6)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Producto')),
            ],
        ),
    ]
