# Generated by Django 3.0.6 on 2020-06-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_vendedor',
            name='role',
            field=models.CharField(choices=[('C', 'Comprador'), ('V', 'Vendedor')], max_length=1),
        ),
    ]
