# Generated by Django 3.0.6 on 2020-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_orden',
            name='descuento',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalle_orden',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
