# Generated by Django 3.0.6 on 2020-06-12 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
