# Generated by Django 3.0.6 on 2020-06-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0003_auto_20200602_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_categoria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto_categoria',
            name='categoria',
            field=models.ManyToManyField(to='mercadito.Categoria'),
        ),
        migrations.RemoveField(
            model_name='producto_categoria',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto_categoria',
            name='producto',
            field=models.ManyToManyField(to='mercadito.Producto'),
        ),
    ]
