# Generated by Django 3.0.6 on 2020-06-02 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0004_auto_20200602_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_comprador',
            name='usuario_comprador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Comprador'),
        ),
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='usuario_vendedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mercadito.Usuario_Vendedor'),
        ),
    ]
