# Generated by Django 3.0.6 on 2020-06-23 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0006_remove_perfil_comprador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_comprador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
