# Generated by Django 3.0.6 on 2020-06-23 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0007_auto_20200623_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_comprador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_comprador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
