# Generated by Django 3.0.6 on 2020-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0008_auto_20200623_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='ruta',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
