# Generated by Django 3.0.6 on 2020-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0009_auto_20200626_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto_categoria',
            name='slug',
            field=models.SlugField(default='test-pcategory'),
            preserve_default=False,
        ),
    ]
