# Generated by Django 3.0.6 on 2020-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0010_auto_20200626_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='portada',
            field=models.ImageField(blank=True, upload_to='portada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
