# Generated by Django 3.0.6 on 2020-06-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0011_auto_20200627_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='portada',
            field=models.ImageField(null=True, upload_to='portada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar'),
        ),
    ]
