# Generated by Django 3.0.6 on 2020-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0012_auto_20200627_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_vendedor',
            name='portada',
            field=models.ImageField(blank=True, default=270620, upload_to='portada'),
            preserve_default=False,
        ),
    ]
