# Generated by Django 3.0.6 on 2020-06-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0013_auto_20200627_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
