# Generated by Django 3.0.6 on 2020-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadito', '0016_auto_20200627_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
